services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TRUSTED_ORIGINS: ${NEXT_PUBLIC_APP_URL}

  ai:
    build:
      context: .
      dockerfile: apps/ai/Dockerfile

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "80:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:2222
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - backend
